services:
  - type: web
    name: stock-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.13
    plan: free
    autoDeploy: true
