services:
  - type: web
    name: stock-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    # ↓ change this:
    pythonVersion: 3.10.13
    plan: free
    autoDeploy: true
